# small
[category."aarch64-linux".small]
divisor = 2000
minimum = 1

[[category."aarch64-linux".small.plans]]
bid = 2.0
plan = "c3.large.arm64"
netboot_url = "https://netboot.nixos.org/dispatch/hydra/hydra.nixos.org/equinix-metal-builders/main/c3-large-arm"

[category."x86_64-linux".small]
divisor = 2000
minimum = 1

[[category."x86_64-linux".small.plans]]
bid = 2.0
plan = "c3.medium.x86"
netboot_url = "https://netboot.nixos.org/dispatch/hydra/hydra.nixos.org/equinix-metal-builders/main/c3-medium-x86"

[[category."x86_64-linux".small.plans]]
bid = 2.0
plan = "m3.large.x86"
netboot_url = "https://netboot.nixos.org/dispatch/hydra/hydra.nixos.org/equinix-metal-builders/main/m3-large-x86"

# big parallel
[category."aarch64-linux".bigparallel]
divisor = 2000
minimum = 1

[[category."aarch64-linux".bigparallel.plans]]
bid = 2.0
plan = "c3.large.arm64"
netboot_url = "https://netboot.nixos.org/dispatch/hydra/hydra.nixos.org/equinix-metal-builders/main/c3-large-arm--big-parallel"

[category."x86_64-linux".bigparallel]
divisor = 2000
minimum = 1

[[category."x86_64-linux".bigparallel.plans]]
bid = 2.0
plan = "c3.medium.x86"
netboot_url = "https://netboot.nixos.org/dispatch/hydra/hydra.nixos.org/equinix-metal-builders/main/c3-medium-x86--big-parallel"

[[category."x86_64-linux".bigparallel.plans]]
bid = 2.0
plan = "m3.large.x86"
netboot_url = "https://netboot.nixos.org/dispatch/hydra/hydra.nixos.org/equinix-metal-builders/main/m3-large-x86--big-parallel"
